#!/bin/bash
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/MuEnriched_20toInf.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/20/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/20/One/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/20/Two/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/20/Three/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/20/Four/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/MuEnriched_30to50.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/30/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/30/One/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/30/Four/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/MuEnriched_50to80.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/50/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/50/One/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/50/Two/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/50/Three/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/50/Four/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/MuEnriched_80to120.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/80/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/80/One/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/80/Two/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/80/Three/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/MuOnes/80/Four/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/EMTuple_20to30.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/20/Zero/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/EMTuple_30to80.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/30/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/30/One/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/EMTuple_80to170.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/80/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/EMTuples/80/One/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/BCTuple_20to30.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/20/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/20/Two/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/20/Three/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/20/Four/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/BCTuple_30to80.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/30/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/30/One/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/BCTuple_80to170.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/80/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/80/Two/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/80/Three/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/80/Four/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/80/FourOne/*.root
hadd -f /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/BCTuple_170toInf.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/170/Zero/*.root /cms/data/store/user/t2/users/mrcarver/LatestFRSyncTuples/bcTuples/170/One/*.root
